version: '3.8'

services:
  # 1. ส่วนของ Database (MySQL)
  mysqldb:
    image: mysql:8.0
    container_name: scam_guard_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: poom1234
      MYSQL_DATABASE: scam_guard_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - scam_guard_network

  # 2. ส่วนของ Backend (Node.js)
  backend:
    build: ./backend
    container_name: scam_guard_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb 
      DB_USER: root
      DB_PASS: poom1234
      DB_NAME: scam_guard_db
      PORT: 3000
      JWT_SECRET: super_secret_scam_guard_key_change_me
    volumes:
      - ./backend:/app          # แก้จาก .:/app เป็น ./backend:/app
      - /app/node_modules       # เพื่อไม่ให้ node_modules ในเครื่องไปทับใน container
    networks:
      - scam_guard_network

# กำหนดชื่อ Network ที่จะใช้
networks:
  scam_guard_network:
    driver: bridge

volumes:
  mysql_data:
